rails_tutorial: "https://www.railstutorial.org/"
rail: "https://rubyonrails.org/"
rails_michaelhartl: "https://www.michaelhartl.com/"
rails_news: "https://news.railstutorial.org/"
rails_contact: "https://www.railstutorial.org/#contact"
rails_help: "https://github.com/mhartl/sample_app_6th_ed/blob/main/HELP.md"
rails_book: "https://www.railstutorial.org/book"
learn_enough: "https://www.learnenough.com/"
screen_cast: "https://screencasts.railstutorial.org/"
